defaults:
  - dataset: mnist
  - model: C4
  - job
  - hydra/launcher: submitit_local
  - launcher: local

paths:
  datadir: /data/ziz/not-backed-up/mhutchin/EquivCNP/data
  logdir: /data/ziz/not-backed-up/mhutchin/EquivCNP/logs/image
  rundir: ${dataset.name}/${model.name}

experiment_name: match_peter_sweep

seed: 0

epochs: 10
finetune_epochs: 0
limit_train_batches: 1.0
batch_size: 28
finetune_batch_size: 5
test_valid_splits: [0.6, 0.4]

min_context_fraction: 0.1
max_context_fraction: 0.5
n_points_fraction: 1.0

log_every_n_steps: 1
flush_logs_every_n_steps: 50
val_check_interval: 0.5
log_gpu_memory: True
debug: False
pretrained_checkpoint: null