defaults:
  - dataset: MNIST
  - model: C4
  - job
  - hydra/launcher: submitit_local
  - launcher: local

paths:
  datadir: /data/ziz/not-backed-up/mhutchin/EquivCNP/data
  logdir: /data/ziz/not-backed-up/mhutchin/EquivCNP/logs/image
  rundir: ${dataset.name}/${model.name}

experiment_name: match_peter_sweep

seed: 0

epochs: 30
batch_size: 16
test_valid_splits: [0.6, 0.4]

min_context: 8
max_context: 392
total_points: 784

log_every_n_steps: 1
flush_logs_every_n_steps: 50
val_check_interval: 0.5
log_gpu_memory: True